# Generated by Django 5.0.1 on 2024-01-25 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infermier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomF', models.CharField(max_length=50)),
                ('prenomF', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomM', models.CharField(max_length=50)),
                ('prenomM', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nss', models.IntegerField(primary_key=True, serialize=False)),
                ('nomP', models.CharField(max_length=50)),
                ('prenomP', models.CharField(max_length=50)),
                ('telP', models.IntegerField()),
                ('adrP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(max_length=100)),
                ('traitement', models.CharField(max_length=100)),
                ('resultat', models.CharField(max_length=100)),
                ('estlier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medecin')),
                ('correspond', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estchargéInf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.infermier')),
                ('estchargéMed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medecin')),
                ('prendre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
    ]
