# Generated by Django 5.0.1 on 2024-01-25 01:28

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateN',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='dateRdv',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='heureRdv',
            field=models.TimeField(default=datetime.time(1, 28, 20, 433881)),
        ),
    ]
