# Generated by Django 5.0.1 on 2024-01-25 23:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_patient_daten_rdv_daterdv_rdv_heurerdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='estchargéInf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.infermier'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='estchargéMed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.medecin'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='heureRdv',
            field=models.TimeField(default=datetime.time(23, 56, 34, 437895)),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='prendre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.patient'),
        ),
    ]
